<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.GenAI" Version="1.5.0" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="Vosk" Version="0.3.38" />
  </ItemGroup>

</Project>
